// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomotarJhuri.Infractructure.Data;

#nullable disable

namespace MomotarJhuri.Infractructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250707100343_CreateUserTableAndSeedSomeData")]
    partial class CreateUserTableAndSeedSomeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomotarJhuri.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dhaka",
                            Email = "sr@gmail.com",
                            Gender = 0,
                            Name = "sr",
                            Nationality = "Bangladeshi",
                            Password = "password",
                            PhoneNumber = "01700000000",
                            PhotoLink = "https://example.com/photo.jpg",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dhaka2",
                            Email = "tf@gmail.com",
                            Gender = 0,
                            Name = "tf",
                            Nationality = "Bangladeshi",
                            Password = "password",
                            PhoneNumber = "01700000000",
                            PhotoLink = "https://example.com/photo.jpg",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
